export const activities = {
  food: [
    'healthy',
    'soup',
    'vegetables',
    'meat',
    'fish',
    'no meal',
    'bread',
    'breakfast',
    'lunch',
    'pizza',
    'sweets',
    'dinner',
    'fruits',
    'chocolate',
  ],
  drink: [
    'water',
    'tea',
    'alcohol',
    'milk',
    'coffee',
    'espresso',
    'juice',
    'pop',
  ],
  fun: [
    'cafe',
    'casino',
    'computer',
    'concert',
    'gaming',
    'makeup',
    'cinema',
    'hairdresser',
    'museum',
    'surfing',
    'watch tv',
    'travel',
    'walking',
    'fighting',
    'peeling apples',
  ],
  leisure: [
    'cars',
    'billiards',
    'bowling',
    'dancing',
    'cooking',
    'guitar',
    'piano',
    'fishing',
    'gardening',
    'camping',
    'sewing',
    'relax',
    'reading',
    'writing',
    'meditation',
    'painting',
  ],
  health: [
    'smokefree',
    'dentist',
    'headache',
    'take meds',
    'smoke',
    'pain',
    'on period',
    'throw up',
    'doctor',
  ],
  social: [
    'argue',
    'cuddle',
    'family',
    'love',
    'friends',
    'meetup',
    'discussion',
    'help',
    'party',
    'date',
    'chat',
    'phone call',
    'sex',
    'pray',
    'talk',
  ],
  media: ['facebook', 'the dark web', 'silk road'],
  work: [
    'college',
    'household',
    'learning',
    'school',
    'university',
    'commute',
    'event',
    'working',
    'meeting',
    'sick leave',
  ],
  occasions: [
    'wedding',
    'birthday',
    'graduation',
    'breakup',
    'funeral',
    'anniversary',
  ],
  sports: [
    'diving',
    'football',
    'cycling',
    'climbing',
    'boxing',
    'basketball',
    'fitness',
    'cricket',
    'tennis',
    'gym',
    'baseball',
    'running',
    'soccer',
    'riding',
    'hiking',
    'swimming',
    'yoga',
  ],
};

export const categories = [
  ['food', 'drink', 'fun', 'leisure'],
  ['health', 'social', 'media', 'work'],
  ['occasions', 'sports'],
];
