export const activities = {
  food: [
    'healthy',
    'soup',
    'vegetables',
    'meat',
    'fish',
    'no meal',
    'bread',
    'breakfast',
    'lunch',
    'pizza',
    'sweets',
    'dinner',
    'fruits',
    'chocolate',
  ],
  drink: ['water', 'tea', 'alcohol', 'milk', 'coffee', 'esspresso'],
  fun: [
    'cafe',
    'casino',
    'computer',
    'concert',
    'gaming',
    'makeup',
    'Cinema',
    'hairdresser',
    'museum',
    'surfing',
    'watch television',
    'travel',
    'walking',
    'fighting',
    'peeling apples',
  ],
  leisure: [
    'Cars',
    'Billiard',
    'Bowling',
    'Dancing',
    'Cooking',
    'Guitar',
    'Piano',
    'Fishing',
    'Gardening',
    'Camping',
    'Sewing',
    'Relax',
    'Readng',
    'Writing',
    'Meditation',
    'Painting',
  ],
  music: [
    'Money',
    'Smokefree',
    'Dentist',
    'Headache',
    'Take meds',
    'Smoke',
    'Pain',
    'Success',
    'Prodcrast',
    'On period',
    'Throw Up',
    'Visit Doctor',
  ],
  social: [
    'Argue',
    'Cuddle',
    'Family',
    'love',
    'friends',
    'Meetup',
    'Discussion',
    'Help',
    'Party',
    'Date',
    'Chat',
    'Phone call',
    'sex',
    'Pray',
    'Talk',
  ],
  media: ['facebook', 'the dark web', 'silk road'],
  work: [
    'College',
    'Household',
    'Learning',
    'School',
    'University',
    'Commute',
    'Event',
    'Working',
    'Meeting',
    'Sick Leave',
  ],
  occasions: [
    'Wedding',
    'Birthday',
    'Graduation',
    'Breakup',
    'Funeral',
    'Anniversary',
  ],
  sports: [
    'Diving',
    'Football',
    'Cycling',
    'Climping',
    'Boxing',
    'Basketball',
    'Fitness',
    'Cricket',
    'Tennis',
    'Gym',
    'Baseball',
    'Running',
    'Soccer',
    'Riding',
    'Hiking',
    'Swimming',
    'Yoga',
  ],
};

export const categories = [
  ['food', 'drink', 'fun', 'leisure'],
  ['music', 'social', 'media', 'work'],
  ['occasions', 'sports'],
];
